version: '2'
services:
    tomcat:
      image: tomcat:8.5.33
      hostname: tomcat
      container_name: tomcat
      restart: always
      ports:
       - "8080:8080"
      expose:
       - "8080"
      volumes:
       - /home/ids/FIWARE_DEVELOPMENT/tomcat/conf:/usr/local/tomcat/conf
       - /home/ids/FIWARE_DEVELOPMENT/tomcat/webapps/:/usr/local/tomcat/webapps
       - /home/ids/FIWARE_DEVELOPMENT/tomcat/logs/:/usr/local/tomcat/logs
      networks:
        ids_connector_network:
          ipv4_address: 172.18.2.7
    mosquitto:
      image: eclipse-mosquitto:1.4.12
      hostname: mosquitto
      container_name: mosquitto
      restart: always
      ports:
       - "1883:1883"
       #- "9001:9001"
      volumes:
       - /home/ids/FIWARE_DEVELOPMENT/mosquitto/config:/mosquitto/config
       - /home/ids/FIWARE_DEVELOPMENT/FIWARE/mosquitto/log:/mosquitto/log
      networks:
        ids_connector_network:
          ipv4_address: 172.18.2.2
    pepIn:
      restart: always
      image: fiware/pep-proxy
      container_name: pepIn
      hostname: pepIn
      volumes:
        - /home/ids/FIWARE_DEVELOPMENT/pepIn/config.js:/opt/fiware-pep-proxy/config.js
      #ports:
        #- "1027:1027"
      #links:
        #- fiware-idm
      depends_on:
        - fiware-idm
      networks:
        ids_connector_network:
          ipv4_address: 172.18.2.5
        idm_network:
          ipv4_address: 172.18.1.4
    iotAgent:
      restart: always
      image: fiware/iotagent-mqtt
      container_name: iotAgent
      hostname: iotAgent
      volumes:
        - /home/ids/FIWARE_DEVELOPMENT/iotAgent/config.js:/opt/iota-mqtt/config.js
      ports:
       - "4041:4041"
      links:
       #- mongo
       #- orion
       - fiware-idm
      networks:
        ids_connector_network:
          ipv4_address: 172.18.2.3
        idm_network:
          ipv4_address: 172.18.1.7
    mongo:
      restart: always
      image: mongo:3.4
      container_name: mongo
      hostname: mongo
      #volumes:
        #- /home/ids/FIWARE_DEVELOPMENT/mongodb/data:/data/db
      command: --nojournal
      networks:
        ids_connector_network:
          ipv4_address: 172.18.2.6
    orion:
      restart: always
      image: fiware/orion
      container_name: orion
      hostname: orion
      #links:
       #- mongo
      ports:
       - "1026:1026"
      command: -dbhost 172.18.2.6
      networks:
        ids_connector_network:
          ipv4_address: 172.18.2.4
    mysql:
      image: mysql/mysql-server:5.7.21
      container_name: mysql
      hostname: mysql
      ports:
        - "3306:3306"
      volumes:
        - /home/ids/FIWARE_DEVELOPMENT/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=idm
        - MYSQL_ROOT_HOST=172.18.1.6
      networks:
        idm_network:
          ipv4_address: 172.18.1.5
    fiware-idm:
      image: fiware/idm
      container_name: idm
      hostname: idm
      ports:
       - "3000:3000"
       - "443:443"
      networks:
        idm_network:
          ipv4_address: 172.18.1.6
      environment:
       - DATABASE_HOST=172.18.1.5
networks:
 ids_connector_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.2.0/24
         gateway: 172.18.2.1
 idm_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.1.0/24
         gateway: 172.18.1.1


